apiVersion: v1
kind: ReplicationController
metadata:
  namespace: production-tools
  labels:
    name: kafka
  name: kafka-controller
spec:
  replicas: 1
  selector:
    name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.5
          env:
            - name: ZOOKEEPER_CONNECT
              value: ca-p-zk01:2181,ca-p-zk02:2181,ca-p-zk03:2181
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/reverbnation/k8s-kafka:0cac3c5137df
          name: kafka
          ports:
            - containerPort: 9092
              name: primary
            - containerPort: 7203
              name: jmx
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
          
